### ISSUE TITLE
Doesn’t work.

### ISSUE THREAD

**Issue by portisum** [dildeolupbiten/TkAstroDb#2] opened 2022-04-19 11:42 UTC
Your program doesn’t work. After the program is run - it just doesn’t show the database.
JSON format is uploaded on the database folder, the program just doesn’t run. 

#

**Comment by dildeolupbiten** [comment] 2022-05-14 21:31
The program works...

You can download the xml database from [AdbExport](http://www.astro.com/adbexport/). Also you need to contact the webmaster of www.astro.com to get a licence of the xml database. After you get a licence, you need to extract the xml database file. Then you need to put this file in Database folder.

**Comment by portisum** [comment] 2022-05-15 12:38
Hi! I have already managed to make it work since I wrote!
I have successfully installed synastry parser too! Works with adb license.
I haven’t figured out how to add my own charts from ex solar fire or
astrolog though.
🧐do I add them as separate json files? I figured I can do that through adb
but still.

However, I have a friend ***@***.*** who has a
problem with installation itself and I can’t figure what’s the problem. We
live in diff countries, I tried my best to explain - nope, still doesn’t
work.
Can you please ask him what’s wrong because I don’t  get what’s up in there
for two weeks now. And he has a famous blog on internet and is a friend
with the astrology podcast dude (125k on YouTube last time I checked). U
might not know them, but they can make your project more well-known😃
I mean, YOUR PROGRAM IS VERY impressive. I’m wondering why ISAAR or
research astrology doesn’t use it. I mean David Cochrane kinda did
something similar, but u know I haven’t heard of any cool research from him
since harmonical astrology.

I have wrote about you to them though and no response!

However, I have wrote about your program to this dude:
Ak1statistical on YouTube (I will not impy a link to not get into spam) he
uses knime + R language to do data science on astrology, you might wanna
check him - he said it’s very useful and great!

2.
Is it you on kaggle with datasets? Because they are very similar. I am
kinda wondering right now - can we do a Convolutional neural network to
analyse that gauqlin’s data set?
I have like three charts that are within 2 weeks with the same ascendant
and these are COMPLETELY different fates, sexual orientations and deaths.
All three - men. The issue is, that I have checked 390 charts of gay males
by hand - nope. 🙄nothing extra. Nothing that makes them separated from one
or another.
NO-thing.

Even if you place asteroids, such as I dunno, Chicago and Filippa (or any
fictional point as like Selena or Proserpina)
nothing SUPER DUPER different. So I have been thinking about CNN, but as
you have already guessed, I’m not a python programmer in any way. Or data
scientist, though knife is pretty easy.

Thank u for your attention !

.S.
воскресенье, 15 мая 2022 г. пользователь dildeolupbiten <
***@***.***> написал:

**Comment by dildeolupbiten** [comment] 2022-05-15 13:52
Hi again,

What exactly is your friend's problem? By the way, if your friend opens an Issue like you did here, we could try to understand his problem. By the way the emails you provided me are not seen.

Also he can use the online application of TkAstoDb using this website [TkAstroDb](http://tkastrodb.herokuapp.com/) until his problem get fixed. It's free to use.

In order to use a derived database in JSON format, you should use TkEnneagram program. The process of loading the database is similar in TkEnneagram. But unlike TkAstroDb, TkEnneagram converts the xml file to json file. So you can use this JSON file with TkAstroDb.

No, it's not me who is on Kaggle with datasets. You can try to develop a program with the XML database that is provided by Astrodienst, such a program that works with a supervised neural network. I've tried building a supervised neural network model before, but the predictions weren't very accurate. More precisely, I faced the underfitting problem. Since I don't have much time these days, I can't focus too much on that subject.

As I said I'm a little busy these days due to work, so I can't spare much time for statistical astrology studies. I will take a look at the page of the friend you mentioned (Ak1Statistical) at a convenient time.

**Comment by portisum** [comment] 2022-05-15 14:36
Okay, thank u!
I have encountered the same thing with CNN (I have used some one else’s
network for it) - too much noise (?).
Thanks once again!
воскресенье, 15 мая 2022 г. пользователь dildeolupbiten <
***@***.***> написал:

**Comment by portisum** [comment] 2022-05-15 20:11
Hi, I have tried your web program, it doesn’t work the same way the pc
version does…

**Comment by dildeolupbiten** [comment] 2022-05-15 23:22
Hi, what did you mean? Of course the interface is a little different. But the functions and the results based on the selections should be same if you use the same version of the database. Please read the documentation of the web interface, the version of the Adb is written there. And probably the Adb version you are using with the desktop application is not same. Nevertheless, the files produced by both apps are compatible.

**Comment by portisum** [comment] 2022-05-16 01:26
I think it will go quicker if you consider me being very stupid :)
😃 But here is the thing - it opens up from Pc and works(!) and the tab
TASKS doesn't open from IPad/IPhone

пн, 16 мая 2022 г. в 02:22, dildeolupbiten ***@***.***>:

**Comment by dildeolupbiten** [comment] 2022-05-16 05:50
The Tasks tab drop downs when you hover your mause on the Tasks tab if you use pc, but it does not hover when you use mobile phones. I dont know how it behaves on Iphone but on android based mobile phones you need to click the Tasks tab to see the drop down menu.

**Comment by portisum** [comment] 2022-05-16 17:16
Thanks for the tip!
By the way, have you seen this?
https://www.kaggle.com/code/gokhanyu/classifying-couples-using-astrological-aspects
I mean this is cool!

пн, 16 мая 2022 г. в 08:50, dildeolupbiten ***@***.***>:

**Comment by dildeolupbiten** [comment] 2022-05-16 18:40
No, i haven't seen that. Thank you for the link. 

By the way, since the issue is resolved, I am closing this issue. 

Have nice days.

**Closed as completed by dildeolupbiten** 2022-05-16 18:40 UTC

**Comment by portisum** [comment] 2022-05-16 21:41
yep, take care! thanks for your programs!

понедельник, 16 мая 2022 г. пользователь dildeolupbiten <
***@***.***> написал:
